$('.owl-carousel').owlCarousel({
    loop:true,
    margin:12,
    nav: false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:4
        },
        1100:{
            items:5
        },
        1400:{
            items:6
        },
        1500:{
            items:7
        },
        1600:{
            items:8
        }
    }
})